version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:15.6.0-ce.0
    container_name: gitlab
    restart: always
    hostname: '172.17.3.45'
    ports:
      - '8282:80'  # HTTP
      - '443:443'  # HTTPS
      - '2222:22'  # SSH
    volumes:
      - ./data/gitlab_data:/var/opt/gitlab:rw     # Persistent data storage
      - ./data/gitlab_logs:/var/log/gitlab:rw  # Log files
      - ./data/etc/gitlab:/etc/gitlab:rw
    shm_size: '256m'
