version: '3.8'

services:
  openproject:
    image: openproject/openproject:15
    container_name: openproject
    ports:
      - "8081:80"
    environment:
      OPENPROJECT_HTTPS: false
      OPENPROJECT_SECRET_KEY_BASE: "secret"
      OPENPROJECT_HOST__NAME: "localhost:8081"
      OPENPROJECT_DEFAULT__LANGUAGE: "en"
      
    volumes:
      - ./pgdata:/var/openproject/pgdata 
      - ./assets:/var/openproject/assets 


# dos2unix backup_op_do_to_local.sh  

# docker cp ./local_backup_op/op_backup.sql openproject:/tmp/op_backup.sql

# psql -U openproject -h 127.0.0.1 -p 5432 -d openproject -f /tmp/op_backup.sql

# psql -h localhost -d openrealdb -U open_real -p 5432 -f /tmp/op_backup.sql