version: '3.8'
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    restart: always
    ports:
      - "8088:80"
    volumes:
      - ./config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://172.17.3.45:8088
      - APP_KEY=base64:Buc7Qf0tvF0sn7gnvpHnfiQOoqOqsTHY96c52v40+cM=
      - DB_HOST=db
      - DB_DATABASE=bookstackrealdb
      - DB_USERNAME=bookstack_real
      - DB_PASSWORD=YU8&35BVI9G88
    depends_on:
      - db
  db:
    image: mysql:5.6
    container_name: bookstack-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=bookstackrealdb
      - MYSQL_USER=bookstack_real
      - MYSQL_PASSWORD=YU8&35BVI9G88
      - host_cache_size=0y
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db:/var/lib/mysql



